# Generated by Django 6.1.1 on 2026-09-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('debt', 'Debt'), ('credit_card', 'Credit Card'), ('emi', 'EMI'), ('grocery', 'Grocery'), ('clothes', 'Clothes'), ('rent', 'Rent'), ('other', 'Other')], max_length=20),
        ),
    ]
