# Generated by Django 6.1.1 on 2026-09-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.creditcard'),
        ),
        migrations.AddField(
            model_name='expense',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.debt'),
        ),
    ]
